name: Build
on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get envoy version
        id: version
        run: |-
          # Get latest envoy version
          ENVOY_VERSION=$(wget -q https://registry.hub.docker.com/v1/repositories/envoyproxy/envoy/tags -O -  | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  | awk -F: '{print $3}' | grep v | grep -v docs | sort -r --version-sort | head -n 1)
          CURRENT_VERSION=$(curl --silent "https://api.github.com/repos/nicholasjackson/envoy-binaries/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')

          echo "::set-output name=version::$ENVOY_VERSION"
          echo "::set-output name=current::$CURRENT_VERSION"
    outputs:
      version: ${{steps.version.outputs.version}}
          
  amd64:
    needs: setup
    if: ${{needs.setup.outputs.version != needs.setup.outputs.current}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download binary
        run: |
          docker create --name envoy envoyproxy/envoy:${{needs.setup.outputs.version}}
          docker cp envoy:/usr/local/bin/envoy binaries/envoy_amd64

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            binaries/envoy_amd64

  arm64:
    needs: setup
    if: ${{needs.setup.outputs.version != needs.setup.outputs.current}}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Download binary
        run: |
          docker create --name envoy envoyproxy/envoy:${{needs.setup.outputs.version}}
          docker cp envoy:/usr/local/bin/envoy binaries/envoy_arm64

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            binaries/envoy_arm64

  release:
    needs: setup
    if: ${{needs.setup.outputs.version != needs.setup.outputs.current}}
    runs-on: ubuntu-latest
    steps:
      - name: Tag release
        uses: mathieudutour/github-tag-action@v5.6
        with:
          tag_prefix: ""
          custom_tag: ${{needs.setup.outputs.version}}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: binaries
          path: binaries/

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            binaries/envoy_amd64
            binaries/envoy_arm64
          tag_name: ${{needs.setup.outputs.version}}