name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download envoy binary
        id: download
        run: |-
          # Get latest envoy version
          ENVOY_VERSION=$(wget -q https://registry.hub.docker.com/v1/repositories/envoyproxy/envoy/tags -O -  | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  | awk -F: '{print $3}' | grep v | grep -v docs | sort -r --version-sort | head -n 1)
          CURRENT_VERSION=$(curl --silent "https://api.github.com/repos/nicholasjackson/envoy-binaries/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')

          if [ $ENVOY_VERSION == $CURRENT_VERSION ]; then
            echo "Envoy binaries are up to date."
            exit 0 
          fi

          docker create --name envoy envoyproxy/envoy:$ENVOY_VERSION
          docker cp envoy:/usr/local/bin/envoy envoy_amd64

          echo "::set-output name=version::$ENVOY_VERSION"
      - name: echo
        run: |
          echo "${{steps.download.outputs.version}}"
      - name: Tag release
        uses: mathieudutour/github-tag-action@v5.6
        with:
          custom_tag: ${{steps.download.outputs.version}}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: envoy_amd64
          tag_name: ${{steps.download.outputs.version}}